# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

avatar = File.new("public/im.jpg")
User.find_or_create_by_email(:email => "a@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "b@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "c@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "d@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "e@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "f@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "g@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "h@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "i@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "j@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "k@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "l@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "m@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "n@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "o@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "p@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "q@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "r@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "s@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "t@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "u@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "v@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "x@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "y@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@z.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "a@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "b@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "c@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "d@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "e@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "f@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "g@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "h@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "i@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "j@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "k@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "l@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "m@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "n@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "o@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "p@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "q@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "r@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "s@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "t@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "u@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "v@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "w@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "x@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "y@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@z.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@a.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@b.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@c.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@d.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@e.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@f.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@g.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@h.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@i.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@j.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@k.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@l.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@m.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@n.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@o.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@p.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@q.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@r.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@s.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@t.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@u.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@v.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@w.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@x.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@y.com", :password => "hola159753", :avatar => avatar)
User.find_or_create_by_email(:email => "z@z.com", :password => "hola159753", :avatar => avatar)

